### PR TITLE
Whitelist certain iframe sources

### LINKED ISSUE #2314: iframes tags being stripped when saving posts
## While trying to do this:

Add an iframe to a Youtube or Vimeo embed using the TinyMCE editor

## I encountered this error:

The published/saved content has the iframe tag disabled and embeds do not appear.

## Some other notes:

Give us some context: 

I am using latest build at head.

An example page with the iframe issue is here:

https://1500wordmtu.com/2018/when-pong-played-humans 

It appears that 8dceeeba2998e0640ba54e1f81f23a6fba41a2c5 included HtmlPurifier.  I believe that enabling

http://htmlpurifier.org/live/configdoc/plain.html#HTML.SafeIframe

and/or 

http://htmlpurifier.org/live/configdoc/plain.html#URI.SafeIframeRegexp

should correct this.

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

0.9.9-a

* What database are you using? (e.g. mongo, mysql, postgres)

mysql

### PR DESCRIPTION
**Pull request by benwerd**
## Here's what I fixed or added:

HTMLPurifier now allows iframes for YouTube, Vimeo, SoundCloud, RadioPublic, and Google Maps by default.

Users can also whitelist other iframe sources using the new `allowedIframes` config setting.

Fixes #2314

## Here's why I did it:

Users should absolutely be allowed to post safe iframes of their choice.

## Checklist:

- [x] This pull request addresses a single issue
- [ ] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [x] I've adhered to Known's style guide
- [x] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [x] I've tested my code in-browser
- [ ] My code contains descriptive comments
- [ ] I've added tests where applicable

### CODE REVIEW

File: Idno/Core/Purifier.php [hunk 1]
```diff
@@ -14,8 +14,22 @@ function init()
...
+            $allowedIframes = [
+                'www.youtube.com/embed/',
+                'player.vimeo.com/video/',
+                'embed.radiopublic.com/e',
+                'w.soundcloud.com/player/',
+                'maps.google.com/'
+            ];
+
+            if (!empty(Idno::site()->config()->allowedIframes) && is_array(Idno::site()->config()->allowedIframes)) {
+                $allowedIframes = array_merge($allowedIframes, Idno::site()->config()->allowedIframes);
```
Comment (mapkyca) [inline Idno/Core/Purifier.php]: I'd be tempted to wrap this in an event trigger, that way plugins can easily extend this. Otherwise lg

Comment (benwerd) [reply Idno/Core/Purifier.php]: :+1: I'll follow up with that
